name: instagram_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0-28.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  image_picker: ^1.0.4
  provider: ^6.0.5
  flutter_3d_controller: ^2.2.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_instagram.png
    - assets/web/dodecahedron.html
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf